server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**,/users/**,/mentors/**
                
            - id: session-service
              uri: lb://SESSION-SERVICE
              predicates:
                - Path=/sessions/**
           
            - id: learning-service
              uri: lb://LEARNING-SERVICE
              predicates:
                - Path=/skills/**,/groups/**,/reviews/**
